import { inject, Injectable } from '@angular/core';
import { Auth, updateProfile, createUserWithEmailAndPassword, authState, signOut } from '@angular/fire/auth';
import { Firestore, doc, setDoc } from '@angular/fire/firestore';
import IUser from '../models/user';
import { delay, filter, map, switchMap } from 'rxjs';
import { ActivatedRoute, NavigationEnd, Router } from '@angular/router';

@Injectable({
  providedIn: 'root',
})
export class AuthService {
  constructor() {
    this.router.events.pipe(
      filter((event) => event instanceof NavigationEnd),
      map((event) => {
        let currentRoute = this.route;
        while (currentRoute.firstChild) {
          currentRoute = currentRoute.firstChild;
        }
        return currentRoute;
      }),
      switchMap((route) => route.data)
    ).subscribe((data) => {
      this.redirect = data['authOnly'] ?? false;
    });
  }
  #auth = inject(Auth);
  #firestore = inject(Firestore);
  authState$ = authState(this.#auth);
  authStateWithDelay$ = this.authState$.pipe(
    delay(1000)
  );
  router = inject(Router);
  route = inject(ActivatedRoute);
  redirect = false;


  async createUSer(userData: IUser) {
    const userCreds = await createUserWithEmailAndPassword(this.#auth,
      userData.email,
      userData.password
    );
    // addDoc func generate the id for us but we want to use the same id for the user generated by the fire auth when the user registered
    await setDoc(doc(this.#firestore, 'users', userCreds.user.uid), {
      name: userData.name,
      email: userData.email,
      age: userData.age,
      phoneNumber: userData.phoneNumber,
    });

    await updateProfile(userCreds.user, { displayName: userData.name })
  }

  async logout($event?: Event) {
    $event?.preventDefault();
    await signOut(this.#auth);

    if (this.redirect) {
      await this.router.navigateByUrl('/');
    }
  }
}
